<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (  
  '237' => 
  array (
    'name' => 'Cameroon',
    'regex' => '/\(237\)\ ?[2368]\d{7,8}$/m',
  ),

  '251' => 
  array (
    'name' => 'Ethiopia',
    'regex' => '/\(251\)\ ?[1-59]\d{8}$/m',
  ),

  '212' => 
  array (
    'name' => 'Morocco',
    'regex' => '/\(212\)\ ?[5-9]\d{8}$/m',
  ),
  
  '258' => 
  array (
    'name' => 'Mozambique',
    'regex' => '/\(258\)\ ?[28]\d{7,8}$/m',
  ),

  '256' => 
  array (
    'name' => 'Uganda',
    'regex' => '/\(256\)\ ?\d{9}$/m',
  ),
);